# Generated by Django 4.0.3 on 2022-03-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
